apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: example-website
  description: This is an example website
  labels:
    system: public-websites
  annotations:
    example.com/service-discovery: artistweb
    circleci.com/project-slug: github/example-org/artist-website
  tags:
    - java
spec:
  type: website
  template:
    version: 1.0.0
    name: Test Template
  team:
    name: Test Team
    productOwner: po@gmail.com
    technicalOwner: ta@gmail.com
